export {default as Container} from './Container/Container'
export {default as Header}from './Header/Header'
export {default as Footer}from './Footer/Footer'
export {default as Home}from './Home/Home'
export {default as About}from './About/About'
export {default as Gallery}from './Gallery/Gallery'
export {default as Admin}from './Admin/Admin'
export {default as Service}from './Service/Service'
export {default as ButtonToUp}from './ButtonToUp/ButtonToUp'

